Added: command line option to configure certificate common name
kurrent-io/es-gencert-cli pull request #16
Opened 2023-03-27 15:56 UTC by yehohanan7

- Provide a command line option to configure certificate's common name
- the default common name will be "eventstoredb-node" as before

Related [ticket](https://github.com/EventStore/es-gencert-cli/issues/14)

2023-03-29 17:17 UTC, dhingrak commented
Can we add common-name in the helpText as well to notify the user if they enter an invalid option? 
https://github.com/EventStore/es-gencert-cli/blob/configure_common_name/certificates/create_node.go#L285.

2023-03-31 08:31 UTC, hayley-jean requested changes
Thanks! The change works but as @dhingrak mentioned, the option just needs to be added to the `--help` output for the command

2023-03-31 09:47 UTC, yehohanan7 commented
> Thanks! The change works but as @dhingrak mentioned, the option just needs to be added to the `--help` output for the command

Updated help output with common name

2023-03-31 10:54 UTC, hayley-jean approved these changes

2023-03-31 13:17 UTC, dhingrak approved these changes

2023-04-03 08:50 UTC, merged