Added: command to generate ca/node certs from config file
kurrent-io/es-gencert-cli pull request #17
Opened 2023-03-30 09:35 UTC by yehohanan7

- adds a new command `create-certs` that reads a config file (default: `./certs.yml`) and generates certs
- the config file can have definition for multiple certification authorities & nodes
- the implementation is kept simple by making the new command act like an orchestrator that simply invokes the existing `create-ca` and `create-node` commands

Related [ticket](https://github.com/EventStore/es-gencert-cli/issues/13)

2023-03-31 09:18 UTC, hayley-jean requested changes

2023-03-31 09:18 UTC, hayley-jean commented on README.md
> +An example config file:
This example config won't work copied straight from the readme as there won't be any certificates in `./tmp`.


How about an example like this to show generating certs for a cluster of nodes as well as an intermediate CA:

```
certificates:
  ca-certs:
    - out: "./root_ca"
    - out: "./intermediate_ca"
      cert-path: "./root_ca/ca.crt"
      key-path: "./root_ca/ca.key"
      validity:
        days: 5
  node-certs:
    - out: "./node1"
      ca-certificate: "./intermediate_ca/ca.crt"
      ca-key: "./intermediate_ca/ca.key"
      ip-addresses: "127.0.0.1,172.20.240.1"
      dns-names: "localhost,eventstore-node1.localhost.com"
    - out: "./node2"
      ca-certificate: "./intermediate_ca/ca.crt"
      ca-key: "./intermediate_ca/ca.key"
      ip-addresses: "127.0.0.2,172.20.240.2"
      dns-names: "localhost,eventstore-node2.localhost.com"
    - out: "./node3"
      ca-certificate: "./intermediate_ca/ca.crt"
      ca-key: "./intermediate_ca/ca.key"
      ip-addresses: "127.0.0.3,172.20.240.3"
      dns-names: "localhost,eventstore-node2.localhost.com"
```

2023-03-31 09:18 UTC, hayley-jean commented on certificates/create_certs.go
> +type Config struct {
It would be better to reuse the `CreateNodeArguments` and `CreateCAArguments` structs for the options used to generate the certs.
Otherwise the `Config` struct in `Create_Certs` would need to be updated any time a new option is added to either of those commands (e.g. `common-name`).

2023-03-31 09:53 UTC, yehohanan7 commented on README.md
> +An example config file:
Good suggestion, changed the readme with the example.

2023-03-31 10:01 UTC, alexeyzimarev commented on README.md
> +An example config file:
```yaml
    - out: "./root_ca"
    - out: "./intermediate_ca"
      cert-path: "./root_ca/ca.crt"
      key-path: "./root_ca/ca.key"
      validity:
        days: 5
```

I am not sure why the output directory needs to be repeated. I think one only needs to specify the output directory for the whole thing and file names for different files, and everything can be optional.

```yaml
    - out: "./node2"
      ca-certificate: "./intermediate_ca/ca.crt"
      ca-key: "./intermediate_ca/ca.key"
      ip-addresses: "127.0.0.2,172.20.240.2"
      dns-names: "localhost,eventstore-node2.localhost.com"
```

There should be no requirement to specify the CA certificate details if the config file already contains the CA file configuration just above. The tool should use the CA file it generated to generate node certs.

2023-03-31 11:04 UTC, yehohanan7 commented on certificates/create_certs.go
> +type Config struct {
Good point, I use the same Arguments structs now.

Also, I have updated the create_certs command to use some reflection magic to generate the arguments dynamically. so every time a new argument is added to the `CreateNodeArguments` or `CreateCAArguments`, there is no need to make any change to `create_certs`

2023-04-03 12:33 UTC, hayley-jean approved these changes

2023-04-05 14:57 UTC, pvanbuijtene approved these changes

2023-04-05 14:57 UTC, merged