Override existing certs when generating from yaml (DEV-77)
kurrent-io/es-gencert-cli pull request #21
Opened 2023-08-28 10:41 UTC by huynhhuuloc129

Fix: [https://github.com/EventStore/es-gencert-cli/issues/18](https://github.com/EventStore/es-gencert-cli/issues/18)
Remove the check for existing folder error.
Change file permissions to allow writing

2023-09-06 22:23 UTC, cdevarenne approved these changes

2023-10-17 23:03 UTC, cdevarenne approved these changes

2023-10-26 07:42 UTC, pvanbuijtene requested changes
A few things have to be fixed in order to get the PR as it's intended.

Besides that I think it would be nice to make `es-gencert-cli` behave more like other tools, like ask if it should overwrite a file when it already exists.

I'm also not 100% sure if the wording with "override" is correct everywhere and maybe should be overwrite. Maybe it would be better to use something like `force` like other tools.

2023-10-26 07:42 UTC, pvanbuijtene commented on certificates/create_ca.go
> +			return fmt.Errorf("output directory '%s' already exists. Use the -override flag to override the existing directory.", outputDir)
Not sure if this is necessary, the directory isn't really overwritten.

2023-10-26 07:42 UTC, pvanbuijtene commented on certificates/create_ca.go
> +func generateCACertificate(years int, days int, outputDir string, caCert *x509.Certificate, caPrivateKey *rsa.PrivateKey, override bool) error {
Looks like `-override` isn't doing much, getting an error while I expect it to be overwritten.

``` 
.\es-gencert-cli.exe create-ca -override true
error writing CA certificate to ca.crt: open ca/ca.crt: Access is denied.
```

2023-10-26 07:42 UTC, pvanbuijtene commented on certificates/create_ca.go
> +	Override          bool   `yaml:"override"`
Would be nice to just have one setting instead of having to repeat it for CA & node certificates.

2023-10-26 07:42 UTC, pvanbuijtene commented on certificates/create_ca_test.go
> +	os.Chmod(path.Join(outputDir, "ca.crt"), 0644)
This change makes the test succeed, but when actually using it it like ` .\es-gencert-cli.exe create-ca -override` it fails. So I guess this has to be moved.

2023-10-26 07:42 UTC, pvanbuijtene commented on certificates/create_node.go
> +			return fmt.Errorf("output directory '%s' already exists. Use the -override flag to override the existing directory.", outputDir)
Don't think the directory is important here, we're overwriting files not directories.

2023-10-26 07:42 UTC, pvanbuijtene commented on certificates/create_certs.go
> +	-override       Override existing CA directory if it exists
Output is not aligned.

2023-10-26 07:42 UTC, pvanbuijtene commented on certificates/create_certs.go
> +	flags.BoolVar(&arguments.Override, "override", false, "Override existing CA directory if it exists")
The following command gives access denied when running twice:
```
.\es-gencert-cli.exe create-certs -config-file .\certs.yml -override
```

2023-10-30 23:13 UTC, cdevarenne approved these changes

2023-11-08 08:59 UTC, pvanbuijtene reviewed
Nice update 👍 a few suggestions.

I like the check for existing files for `create-certs`, would be nice to have the same for the other 2 commands. Think it would make it more consistent and overall better usage experience. Would you mind adding it?

2023-11-08 08:59 UTC, pvanbuijtene commented on certificates/create_certs.go
> +		go checkFile(fmt.Sprintf("%s", node.CACertificatePath))
Why not directly use `node.CACertificatePath` ? 🤔

2023-11-08 08:59 UTC, pvanbuijtene commented on certificates/create_certs.go
> +		go checkFile(fmt.Sprintf("%s/node.crt", node.OutputDir))
Is there a reason for not using `path.Join` here ?

2023-11-08 08:59 UTC, pvanbuijtene commented on certificates/create_certs.go
> +	// error. Otherwise, it returns nil, indicating that certificate generation
typo
```suggestion
	// error. Otherwise, it returns false, indicating that certificate generation
```

2023-11-08 09:21 UTC, w1am commented on certificates/create_certs.go
> +		go checkFile(fmt.Sprintf("%s", node.CACertificatePath))
Good point! I'll make that change

2023-11-08 09:21 UTC, w1am commented on certificates/create_certs.go
> +		go checkFile(fmt.Sprintf("%s/node.crt", node.OutputDir))
Good point!

2023-11-08 09:22 UTC, w1am commented on certificates/create_certs.go
> +	// error. Otherwise, it returns nil, indicating that certificate generation
Good catch!

2023-11-14 21:03 UTC, cdevarenne approved these changes

2023-11-20 09:22 UTC, pvanbuijtene approved these changes

2023-11-20 09:25 UTC, merged